default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: mini-proj_development

test:
  <<: *default
  database: mini-proj_test

production:
  <<: *default
  database: mini-proj_production
