# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf35a854a8f67bb1ca97008b1b42680444991b41bb165de1cee4499dd413f0b89357b00e47c6ee33f8a44a7d81bb3dbe3b461cafc728449ecc6c0365ba655e0d

test:
  secret_key_base: a7ffe4a26ac331a58f6fcaf32abf66858e4d60b1261b9eead5a38700e16e77c7a80a409fb0ecd4c3691f679be0deb9924079d367f660e14f8d0a1b1b04d5bff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
